# -*- coding: utf-8 -*-
"""FinalOptimGraphing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TlycmJMTP8qdAxBui_PE1pR02gLcSOV5
"""

import sympy as sp
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import linear_sum_assignment
from scipy.spatial.distance import cdist


x1,x2= sp.symbols('x1 x2')
x,y= sp.symbols('x y') #ground truth variables
w,v= sp.symbols('w v')  #generated model variables

def expand_expression(expr):
    try:
        expr= expr.doit()
    except:
        pass
    return sp.expand(expr)


def canonical_constraint(constraint):
    expr= constraint.lhs-constraint.rhs
    return expand_expression(expr)


#convert different forms
def matrix_to_constraints(A,vars_vec,b):
    constraints= []
    for i in range(A.shape[0]):
        lhs= sum(A[i, j]*vars_vec[j] for j in range(A.shape[1]))
        constraints.append(sp.Le(lhs, b[i]))
    return constraints


def indexed_to_constraints(W,coeffs_dict,vars_list,rhs_dict):
    constraints= []
    for w in W:
        lhs= sum(coeffs_dict[v][w] * v for v in vars_list)
        constraints.append(sp.Le(lhs, rhs_dict[w]))
    return constraints


def normalize_model(model):
    constraints= []

    for c in model["constraints"]:
        #if already expanded constraint
        if isinstance(c,sp.Rel):
            constraints.append(c)

        #if in matrix form
        elif isinstance(c,dict) and c["type"]== "matrix":
            constraints+= matrix_to_constraints(c["A"],c["vars"],c["b"])

        #if in indexed compact form
        elif isinstance(c,dict) and c["type"]== "indexed":
            constraints+= indexed_to_constraints(
                c["W"],c["coeffs"],c["vars"],c["rhs"]
            )

    return {
        "objective": expand_expression(model["objective"]),
        "constraints": constraints
    }


#extract all variables in model
def extract_variables(model):
    vars_set= set()
    vars_set |= model["objective"].free_symbols

    for c in model["constraints"]:
        vars_set |= c.free_symbols

    return sorted(list(vars_set),key=lambda s:str(s))


#normalize scaled and sign-reversed constraints
def normalize_constraint(expr,variables):
    coeffs= np.array([float(expr.coeff(v)) for v in variables])
    const= float(expr.subs({v: 0 for v in variables}))

    vec= np.append(coeffs,const)

    if vec[-1]< 0:
        vec= -vec

    norm= np.linalg.norm(vec)

    if norm== 0:
        return vec

    return vec/norm


#build variable features
def build_variable_features(model):
    variables= extract_variables(model)
    obj_expr= sp.expand(model["objective"])

    constraints= [canonical_constraint(c) for c in model["constraints"]]
    norm_constraints= [normalize_constraint(c, variables) for c in constraints]

    #order-invariant sorting
    norm_constraints= sorted(
        norm_constraints,
        key=lambda row: tuple(np.round(row, 6))
    )

    features= {}

    for i,var in enumerate(variables):
        obj_coef= float(obj_expr.coeff(var))

        participation= []
        count= 0

        for nc in norm_constraints:
            coef = nc[i]
            participation.append(coef)

            if abs(coef) > 1e-6:
                count+= 1

        features[var]= np.array(
            [obj_coef]+ participation+ [count]
        )

    return features

#soft matching
def match_variables(features_ground,features_variant):
    gt_vars= list(features_ground.keys())
    llm_vars= list(features_variant.keys())

    A= np.array([features_ground[v] for v in gt_vars])
    B= np.array([features_variant[v] for v in llm_vars])

    #pad dimensions when missing constraint/coeffecient
    max_len= max(A.shape[1], B.shape[1])

    if A.shape[1]< max_len:
        A = np.pad(A,((0,0),(0,max_len-A.shape[1])))

    if B.shape[1]< max_len:
        B = np.pad(B,((0,0),(0,max_len-B.shape[1])))

    cost_matrix= cdist(A,B,metric='euclidean')

    row_ind,col_ind= linear_sum_assignment(cost_matrix)

    mapping= {}

    for i,j in zip(row_ind,col_ind):
        mapping[llm_vars[j]]= gt_vars[i]

    return mapping


#apply relabeling based on formed features
def relabel_model(model,mapping):
    new_obj= model["objective"]

    for old,new in mapping.items():
        new_obj= new_obj.subs(old,new)

    new_constraints= []

    for c in model["constraints"]:
        new_c= c
        for old,new in mapping.items():
            new_c= new_c.subs(old,new)
        new_constraints.append(new_c)

    return {
        "objective": new_obj,
        "constraints": new_constraints
    }

#rename matched variables to a standardized name (VAR_i)
def relabel_model_canonical(model):
    variables= extract_variables(model)

    canonical_map= {}

    for i, var in enumerate(variables):
        canonical_map[var]= sp.Symbol(f"VAR_{i}")

    new_objective= model["objective"]

    for old_var,new_var in canonical_map.items():
        new_objective= new_objective.subs(old_var,new_var)

    new_constraints= []

    for constraint in model["constraints"]:
        new_constraint= constraint

        for old_var,new_var in canonical_map.items():
            new_constraint= new_constraint.subs(old_var,new_var)

        new_constraints.append(new_constraint)

    return {
        "objective": new_objective,
        "constraints": new_constraints
    }

#shared-variable graph
def build_model_graph(model,name):

    G=nx.DiGraph()
    G.add_node("MODEL",type="model")

    variables= extract_variables(model)

    for v in variables:
        G.add_node(str(v),type="variable")

    G.add_node("OBJECTIVE",type="objective")
    G.add_edge("OBJECTIVE","MODEL")

    obj_expr= sp.expand(model["objective"])

    for v in variables:
        coef= float(obj_expr.coeff(v))

        if coef!= 0:
            coef_node= f"obj_coef_{v}"

            G.add_node(coef_node,value=coef)
            G.add_edge(coef_node,str(v))
            G.add_edge(str(v),"OBJECTIVE")

    for i,c in enumerate(model["constraints"]):

        cname= f"C{i+1}"

        G.add_node(cname,type="constraint")
        G.add_edge(cname,"MODEL")

        expr= canonical_constraint(c)

        for v in variables:
            coef= float(expr.coeff(v))

            if coef!=0:
                coef_node= f"{cname}_coef_{v}"

                G.add_node(coef_node,value=coef)
                G.add_edge(coef_node,str(v))
                G.add_edge(str(v),cname)

        constant= float(expr.subs({v: 0 for v in variables}))
        const_node= f"{cname}_const"

        G.add_node(const_node,value=constant)
        G.add_edge(const_node,cname)

    return G

#bipartite graph
def build_bipartite_graph(model,name):

    G= nx.DiGraph()
    G.add_node("MODEL",type="model")

    variables= extract_variables(model)

    for v in variables:
        G.add_node(str(v),type="variable")

    G.add_node("OBJECTIVE",type="objective")
    G.add_edge("OBJECTIVE","MODEL")

    obj_expr= sp.expand(model["objective"])

    for v in variables:
        coef= float(obj_expr.coeff(v))

        if coef!= 0:
            G.add_edge(str(v),"OBJECTIVE",weight=coef)

    for i,c in enumerate(model["constraints"]):

        cname= f"C{i+1}"

        G.add_node(cname,type="constraint")
        G.add_edge(cname,"MODEL")

        expr= canonical_constraint(c)

        for v in variables:
            coef= float(expr.coeff(v))

            if coef!= 0:
                G.add_edge(str(v),cname,weight=coef)

        constant= float(expr.subs({v: 0 for v in variables}))
        const_node= f"{cname}_const"

        G.add_node(const_node,value=constant)
        G.add_edge(const_node,cname)

    return G

def draw_side_by_side(G1,G2,title):

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))

    pos1 = nx.spring_layout(G1, seed=42)

    labels1 = {}
    for node, data in G1.nodes(data=True):
        labels1[node] = f"{node}\n{data['value']}" if "value" in data else node

    nx.draw(
        G1,
        pos1,
        ax=axes[0],
        with_labels=False,
        node_size=2600,
        node_color="lightgreen"
    )

    nx.draw_networkx_labels(G1, pos1, labels1, ax=axes[0])

    axes[0].set_title(title + " (Original)")

    pos2 = nx.spring_layout(G2, seed=42)

    labels2 = {}
    for node, data in G2.nodes(data=True):
        labels2[node] = f"{node}\n{data['value']}" if "value" in data else node

    edge_labels = {
        (u, v): d["weight"]
        for u, v, d in G2.edges(data=True)
        if "weight" in d
    }

    nx.draw(
        G2,
        pos2,
        ax=axes[1],
        with_labels=False,
        node_size=2600,
        node_color="lightblue"
    )

    nx.draw_networkx_labels(G2, pos2, labels2, ax=axes[1])
    nx.draw_networkx_edge_labels(G2, pos2, edge_labels=edge_labels, ax=axes[1])

    axes[1].set_title(title + " (Bipartite)")

    plt.tight_layout()
    plt.show()


#ground truth model
ground_truth= {
    "objective": 10*x + 12*y,
    "constraints": [
        sp.Le(5*x + 4*y, 50),
        sp.Le(2*x + 4*y, 30),
        sp.Le(x + 2*y, 20),
        sp.Ge(x, 0),
        sp.Ge(y, 0)
    ]
}


#LLM-generated variants
variant_reordered= {
    "objective": 10*w + 12*v,
    "constraints": [
        sp.Le(4*v + 5*w, 50),
        sp.Le(4*v + 2*w, 30),
        sp.Le(2*v + w, 20),
        sp.Ge(w, 0),
        sp.Ge(v, 0)
    ]
}

variant_missing_constraint= {
    "objective": 10*w + 12*v,
    "constraints": [
        sp.Le(5*w + 4*v, 50),
        sp.Le(2*w + 4*v, 30),
        sp.Ge(w, 0),
        sp.Ge(v, 0)
    ]
}

variant_scaled_constraint= {
    "objective": 10*w + 12*v,
    "constraints": [
        sp.Le(10*w + 8*v, 100),
        sp.Le(2*w + 4*v, 30),
        sp.Le(w + 2*v, 20),
        sp.Ge(w, 0),
        sp.Ge(v, 0)
    ]
}

variant_wrong_constraint= {
    "objective": 10*w + 12*v,
    "constraints": [
        sp.Le(5*w + 6*v, 50),  #incorrect coefficient (6)
        sp.Le(2*w + 4*v, 30),
        sp.Le(w + 2*v, 20),
        sp.Ge(w, 0),
        sp.Ge(v, 0)
    ]
}


models={
    "Ground Truth":ground_truth,
    "Reordered Constraints":variant_reordered,
    "Missing Constraint":variant_missing_constraint,
    "Scaled Constraint":variant_scaled_constraint,
    "Wrong Constraint":variant_wrong_constraint
}

##testing
normalized_models= {
    name: normalize_model(model)
    for name,model in models.items() }

reference_name= "Ground Truth"
reference_model= normalized_models[reference_name]

reference_features= build_variable_features(reference_model)

graphs={}
bipartite_graphs={}

for name,model in normalized_models.items():

    if name== reference_name:
        aligned_model= model
        mapping= {var: var for var in extract_variables(model)}

    else:
        candidate_features= build_variable_features(model)

        mapping= match_variables(reference_features,candidate_features)

        print(f"\n{name} variable matching:")
        for old_var, new_var in mapping.items():
            print(f"  {old_var} -> {new_var}")

        aligned_model= relabel_model(model,mapping)

    aligned_model= relabel_model_canonical(aligned_model)

    graphs[name]= build_model_graph(aligned_model,name)
    bipartite_graphs[name]= build_bipartite_graph(aligned_model,name)

    print(f"\n{name} aligned objective:")
    print(aligned_model["objective"])


#now draw all graphs
for name in graphs:
    draw_side_by_side(
        graphs[name],
        bipartite_graphs[name],
        name
    )

