In [1]:
from  my_graphs import graphs
from grakel import Graph, OddSth  
from grakel.kernels import WeisfeilerLehman, VertexHistogram
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from OptimModelGraphs import graphs_math

{x2, x1}
{x2, x1}
{x2, x1}
{x2, x1}
{x, y}


In [ ]:
def nx_to_grakel(graph):
    edges= list(graph.edges())
    node_labels= {}
    for node in graph.nodes():
        data_type=graph.nodes[node]
        print(data_type)
        if "value" in data_type:
            node_labels[node]=data_type["value"]
        elif "type" in data_type:
            if data_type.get("type")=="variable":
                node_labels[node] = str(node)

            elif data_type.get("type")=="constraint":
                node_labels[node] = node 
                
            else:
                node_labels[node] = f"{data_type['type']}_{node}"
        else:
            node_labels[node]=str(node)

    print("\n")
    for node in node_labels:
        print(node)
    return Graph(edges, node_labels=node_labels)

In [26]:
math_grakel_graphs= [nx_to_grakel(g) for g in graphs_math.values()]

{'type': 'model'}
{'type': 'variable'}
{'type': 'variable'}
{'type': 'objective'}
{'value': 12.0}
{'value': 10.0}
{'type': 'constraint'}
{'value': 4.0}
{'value': 5.0}
{'value': -50.0}
{'type': 'constraint'}
{'value': 4.0}
{'value': 2.0}
{'value': -30.0}
{'type': 'constraint'}
{'value': 2.0}
{'value': 1.0}
{'value': -20.0}
{'type': 'constraint'}
{'value': 0.0}
{'value': 1.0}
{'value': 0.0}
{'type': 'constraint'}
{'value': 1.0}
{'value': 0.0}
{'value': 0.0}


MODEL
x2
x1
OBJECTIVE
obj_coef_x2
obj_coef_x1
C1
C1_coef_x2
C1_coef_x1
C1_const
C2
C2_coef_x2
C2_coef_x1
C2_const
C3
C3_coef_x2
C3_coef_x1
C3_const
C4
C4_coef_x2
C4_coef_x1
C4_const
C5
C5_coef_x2
C5_coef_x1
C5_const
{'type': 'model'}
{'type': 'variable'}
{'type': 'variable'}
{'type': 'objective'}
{'value': 12.0}
{'value': 10.0}
{'type': 'constraint'}
{'value': 4.0}
{'value': 5.0}
{'value': -50.0}
{'type': 'constraint'}
{'value': 4.0}
{'value': 2.0}
{'value': -30.0}
{'type': 'constraint'}
{'value': 0.0}
{'value': 1.0}
{'value': 0.0}


In [9]:
odd_kernel_math = OddSth(h=10, normalize=True)
sim_math = odd_kernel_math.fit_transform(math_grakel_graphs)
print("OddSth graph_kel")
print("ground truth with ground truth",sim_math[0,0])
print("ground truth with var1: {:.2f}".format(sim_math[0,1]))
print("ground truth with var2: {:.2f}".format(sim_math[0,2]))
print("ground truth with var3: {:.2f}".format(sim_math[0,3]))
print("ground truth with var4: {:.2f}".format(sim_math[0,4]))

OddSth graph_kel
ground truth with ground truth 1.0
ground truth with var1: 0.99
ground truth with var2: 1.00
ground truth with var3: 0.99
ground truth with var4: 1.00


In [10]:
wl_kernel_math = WeisfeilerLehman(n_iter=10, base_graph_kernel=VertexHistogram, normalize=True)
sim_math = wl_kernel_math.fit_transform(math_grakel_graphs)
print("WL graph_kel")
print("ground truth with ground truth",sim_math[0,0])
print("ground truth with var1: {:.2f}".format(sim_math[0,1]))
print("ground truth with var2: {:.2f}".format(sim_math[0,2]))
print("ground truth with var3: {:.2f}".format(sim_math[0,3]))
print("ground truth with var4: {:.2f}\n".format(sim_math[0,4]))

TypeError: '<' not supported between instances of 'str' and 'float'

In [21]:

def nx_to_grakel(graph):
    edges= list(graph.edges())
    print(edges)
    node_labels= {node: graph.nodes[node].get("label", str(node)) for node in graph.nodes()}
    print(node_labels)
    for node in node_labels:
        print(node)
    return Graph(edges, node_labels=node_labels)


In [22]:
math_grakel_graphs= [nx_to_grakel(g) for g in graphs_math.values()]

[('x2', 'OBJECTIVE'), ('x2', 'C1'), ('x2', 'C2'), ('x2', 'C3'), ('x2', 'C4'), ('x2', 'C5'), ('x1', 'OBJECTIVE'), ('x1', 'C1'), ('x1', 'C2'), ('x1', 'C3'), ('x1', 'C4'), ('x1', 'C5'), ('OBJECTIVE', 'MODEL'), ('obj_coef_x2', 'x2'), ('obj_coef_x1', 'x1'), ('C1', 'MODEL'), ('C1_coef_x2', 'x2'), ('C1_coef_x1', 'x1'), ('C1_const', 'C1'), ('C2', 'MODEL'), ('C2_coef_x2', 'x2'), ('C2_coef_x1', 'x1'), ('C2_const', 'C2'), ('C3', 'MODEL'), ('C3_coef_x2', 'x2'), ('C3_coef_x1', 'x1'), ('C3_const', 'C3'), ('C4', 'MODEL'), ('C4_coef_x2', 'x2'), ('C4_coef_x1', 'x1'), ('C4_const', 'C4'), ('C5', 'MODEL'), ('C5_coef_x2', 'x2'), ('C5_coef_x1', 'x1'), ('C5_const', 'C5')]
{'MODEL': 'MODEL', 'x2': 'x2', 'x1': 'x1', 'OBJECTIVE': 'OBJECTIVE', 'obj_coef_x2': 'obj_coef_x2', 'obj_coef_x1': 'obj_coef_x1', 'C1': 'C1', 'C1_coef_x2': 'C1_coef_x2', 'C1_coef_x1': 'C1_coef_x1', 'C1_const': 'C1_const', 'C2': 'C2', 'C2_coef_x2': 'C2_coef_x2', 'C2_coef_x1': 'C2_coef_x1', 'C2_const': 'C2_const', 'C3': 'C3', 'C3_coef_x2': 'C3

{'MODEL': 'MODEL', 'x2': 'x2', 'x1': 'x1', 'OBJECTIVE': 'OBJECTIVE', 'obj_coef_x2': 'obj_coef_x2', 'obj_coef_x1': 'obj_coef_x1', 'C1': 'C1', 'C1_coef_x2': 'C1_coef_x2', 'C1_coef_x1': 'C1_coef_x1', 'C1_const': 'C1_const', 'C2': 'C2', 'C2_coef_x2': 'C2_coef_x2', 'C2_coef_x1': 'C2_coef_x1', 'C2_const': 'C2_const', 'C3': 'C3', 'C3_coef_x2': 'C3_coef_x2', 'C3_coef_x1': 'C3_coef_x1', 'C3_const': 'C3_const', 'C4': 'C4', 'C4_coef_x2': 'C4_coef_x2', 'C4_coef_x1': 'C4_coef_x1', 'C4_const': 'C4_const', 'C5': 'C5', 'C5_coef_x2': 'C5_coef_x2', 'C5_coef_x1': 'C5_coef_x1', 'C5_const': 'C5_const'}

{'MODEL': 'model', 'x2': 'variable', 'x1': 'variable', 'OBJECTIVE': 'objective', 'obj_coef_x2': 12.0, 'obj_coef_x1': 10.0, 'C1': 'constraint', 'C1_coef_x2': 4.0, 'C1_coef_x1': 5.0, 'C1_const': -50.0, 'C2': 'constraint', 'C2_coef_x2': 4.0, 'C2_coef_x1': 2.0, 'C2_const': -30.0, 'C3': 'constraint', 'C3_coef_x2': 2.0, 'C3_coef_x1': 1.0, 'C3_const': -20.0, 'C4': 'constraint', 'C4_coef_x2': 0.0, 'C4_coef_x1': 1.0, 'C4_const': 0.0, 'C5': 'constraint', 'C5_coef_x2': 1.0, 'C5_coef_x1': 0.0, 'C5_const': 0.0}